version: '3'

services:

    redis:
        image: redis:6.0.16
        container_name: redis_jar
        command: bash -c "redis-server --save"
        ports:
            - "6379:6379"      
            
    django_channels:
        # docker run --rm -it -p 8000:8000 django_simple /bin/sh
        # docker run --rm -it -p 8000:8000 django_simple bash        
        
        build:
            context: django_channels
        container_name: django_channels_jar
        # command: python manage.py runserver 0.0.0.0:8000

        command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
        # command: uvicorn --workers=8 --port 8000 --host 0.0.0.0 prototype_project.asgi:application
        # command: uvicorn --port 8000 --host 0.0.0.0 prototype_project.asgi:application
        # command: gunicorn -w 8 -b 0.0.0.0:8000 --preload prototype_project.asgi:application -k uvicorn.workers.UvicornWorker

        # command: gunicorn -w 8 -b 0.0.0.0:8000 project.wsgi:application -k meinheld.gmeinheld.MeinheldWorker      
        image: django_channels_image        
        ports:
            - "8000:8000"    
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        deploy:
            mode: replicated
            replicas: 4
            
    django_channels_1:
        command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
        image: django_channels_image
        depends_on:
            - redis   
    django_channels_2:
        command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
        image: django_channels_image
        depends_on:
            - redis  
    django_channels_3:
        command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
        image: django_channels_image
        depends_on:
            - redis      

    # django_channels_4:
    #     command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
    #     image: django_channels_image
    #     depends_on:
    #         - redis   
    # django_channels_5:
    #     command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
    #     image: django_channels_image
    #     depends_on:
    #         - redis  
    # django_channels_6:
    #     command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
    #     image: django_channels_image
    #     depends_on:
    #         - redis   
    # django_channels_7:
    #     command: daphne -b 0.0.0.0 -p 8000 prototype_project.asgi:application
    #     image: django_channels_image
    #     depends_on:
    #         - redis     

    haproxy:
        # build:
        #     context: HAproxy
        image: haproxy_image
        # command: tail -f > /dev/null
        ports:
            - "9000:8000"     
        depends_on:
            - django_channels          
            - django_channels_1          
            - django_channels_2          
            - django_channels_3               
    
    nginx:        
        build:
            context: nginx    
        image: nginx_image
        # image: nginx:latest
        container_name: nginx_balancer
        working_dir: /etc/nginx/conf.d
        # command: bash        
        # stdin_open: true
        # tty: true
        # volumes:
        #     - /.pentest/nginx:/etc/nginx/conf.d
            # - ./nginx:/etc/nginx/conf.d
            # - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        ports:
            - "8008:8000"
        depends_on:
            - django_channels          
            - django_channels_1          
            - django_channels_2          
            - django_channels_3          

