version: '3'

services:
    empty_django:
        # &base_django

        # docker run --rm -it -p 8000:8000 django_simple /bin/sh
        # docker run --rm -it -p 8000:8000 django_simple bash        
        
        build:
            context: django
        container_name: django_simple
        # command: python manage.py runserver 0.0.0.0:8000
        # command: waitress-serve --listen=*:8000 --threads=8 project.wsgi:application        
        # command: gunicorn -w 8 -b 0.0.0.0:8000 --preload project.asgi:application -k uvicorn.workers.UvicornWorker                
        # command: gunicorn -w 8 -b 0.0.0.0:8000 project.wsgi
        command: gunicorn -w 1 -b 0.0.0.0:8000 project.wsgi:application -k meinheld.gmeinheld.MeinheldWorker      
        image: django_simple
        ports:
            - "8000:8000"

    redis:
        image: redis:6.0.16
        container_name: redis_jar
        ports:
            - "6379:6379"                       

    django_template:
        &base_django  
        build:
            context: django_channels
        # container_name: django_channels_jar
        command: gunicorn -w 1 -b 0.0.0.0:8000 prototype_project.wsgi:application -k meinheld.gmeinheld.MeinheldWorker      
        image: django_channels_image
        ports:
            - "8001:8000"          
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        deploy:
            mode: replicated
            replicas: 4
    